// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateFeatureComment implements createFeatureComment operation.
//
// Create a new comment on a feature.
//
// POST /features/{feature_id}/comments
func (UnimplementedHandler) CreateFeatureComment(ctx context.Context, req *CommentCreateRequest, params CreateFeatureCommentParams) (r *CommentResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateFeatureRequirement implements createFeatureRequirement operation.
//
// Create a new requirement for a feature.
//
// POST /features/{feature_id}/requirements
func (UnimplementedHandler) CreateFeatureRequirement(ctx context.Context, req *RequirementCreateRequest, params CreateFeatureRequirementParams) (r *RequirementResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateIdeaComment implements createIdeaComment operation.
//
// Create a new internal comment on an idea.
//
// POST /ideas/{idea_id}/comments
func (UnimplementedHandler) CreateIdeaComment(ctx context.Context, req *CommentCreateRequest, params CreateIdeaCommentParams) (r *CommentResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProduct implements createProduct operation.
//
// Create a new product or product line.
//
// POST /products
func (UnimplementedHandler) CreateProduct(ctx context.Context, req *ProductCreateRequest) (r *ProductResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProductGoal implements createProductGoal operation.
//
// Create a new goal in a product.
//
// POST /products/{product_id}/goals
func (UnimplementedHandler) CreateProductGoal(ctx context.Context, req *GoalCreateRequest, params CreateProductGoalParams) (r *GoalResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProductInitiative implements createProductInitiative operation.
//
// Create a new initiative in a product.
//
// POST /products/{product_id}/initiatives
func (UnimplementedHandler) CreateProductInitiative(ctx context.Context, req *InitiativeCreateRequest, params CreateProductInitiativeParams) (r *InitiativeResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProductStrategicModel implements createProductStrategicModel operation.
//
// Create a new strategic model in a product.
//
// POST /products/{product_id}/strategy_models
func (UnimplementedHandler) CreateProductStrategicModel(ctx context.Context, req *StrategicModelCreateRequest, params CreateProductStrategicModelParams) (r *StrategicModelResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateReleaseEpic implements createReleaseEpic operation.
//
// Create a new epic in a release.
//
// POST /releases/{release_id}/epics
func (UnimplementedHandler) CreateReleaseEpic(ctx context.Context, req *EpicCreateRequest, params CreateReleaseEpicParams) (r *EpicResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateReleaseFeature implements createReleaseFeature operation.
//
// Create a new feature in a release.
//
// POST /releases/{release_id}/features
func (UnimplementedHandler) CreateReleaseFeature(ctx context.Context, req *FeatureCreateRequest, params CreateReleaseFeatureParams) (r *FeatureResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteComment implements deleteComment operation.
//
// Delete a comment.
//
// DELETE /comments/{comment_id}
func (UnimplementedHandler) DeleteComment(ctx context.Context, params DeleteCommentParams) error {
	return ht.ErrNotImplemented
}

// DeleteRequirement implements deleteRequirement operation.
//
// Delete a requirement.
//
// DELETE /requirements/{requirement_id}
func (UnimplementedHandler) DeleteRequirement(ctx context.Context, params DeleteRequirementParams) error {
	return ht.ErrNotImplemented
}

// GetComment implements getComment operation.
//
// Get a specific comment by ID.
//
// GET /comments/{comment_id}
func (UnimplementedHandler) GetComment(ctx context.Context, params GetCommentParams) (r GetCommentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCurrentUser implements getCurrentUser operation.
//
// Get the currently authenticated user.
//
// GET /me
func (UnimplementedHandler) GetCurrentUser(ctx context.Context) (r *UserResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEpic implements getEpic operation.
//
// Get a specific epic by ID or reference number.
//
// GET /epics/{epic_id}
func (UnimplementedHandler) GetEpic(ctx context.Context, params GetEpicParams) (r GetEpicRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFeature implements getFeature operation.
//
// Get a specific feature by ID or reference number.
//
// GET /features/{feature_id}
func (UnimplementedHandler) GetFeature(ctx context.Context, params GetFeatureParams) (r GetFeatureRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGoal implements getGoal operation.
//
// Get a specific goal by ID or reference number.
//
// GET /goals/{goal_id}
func (UnimplementedHandler) GetGoal(ctx context.Context, params GetGoalParams) (r GetGoalRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetIdea implements getIdea operation.
//
// Get a specific idea by ID.
//
// GET /ideas/{idea_id}
func (UnimplementedHandler) GetIdea(ctx context.Context, params GetIdeaParams) (r *IdeaResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInitiative implements getInitiative operation.
//
// Get a specific initiative by ID or reference number.
//
// GET /initiatives/{initiative_id}
func (UnimplementedHandler) GetInitiative(ctx context.Context, params GetInitiativeParams) (r GetInitiativeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProduct implements getProduct operation.
//
// Get a specific product by ID.
//
// GET /products/{product_id}
func (UnimplementedHandler) GetProduct(ctx context.Context, params GetProductParams) (r *ProductResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRelease implements getRelease operation.
//
// Get a specific release by ID.
//
// GET /releases/{release_id}
func (UnimplementedHandler) GetRelease(ctx context.Context, params GetReleaseParams) (r *ReleaseResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRequirement implements getRequirement operation.
//
// Get a specific requirement by ID or reference number.
//
// GET /requirements/{requirement_id}
func (UnimplementedHandler) GetRequirement(ctx context.Context, params GetRequirementParams) (r GetRequirementRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStrategicModel implements getStrategicModel operation.
//
// Get a specific strategic model by ID or reference number.
//
// GET /strategy_models/{strategy_model_id}
func (UnimplementedHandler) GetStrategicModel(ctx context.Context, params GetStrategicModelParams) (r GetStrategicModelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUser implements getUser operation.
//
// Get a specific user by ID.
//
// GET /users/{user_id}
func (UnimplementedHandler) GetUser(ctx context.Context, params GetUserParams) (r *UserResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListCustomFieldDefinitions implements listCustomFieldDefinitions operation.
//
// Returns all custom field definitions across all products.
//
// GET /custom_field_definitions
func (UnimplementedHandler) ListCustomFieldDefinitions(ctx context.Context) (r *CustomFieldDefinitionListResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListCustomFieldOptions implements listCustomFieldOptions operation.
//
// Returns available options for select/choice custom fields.
//
// GET /custom_field_definitions/{id}/options
func (UnimplementedHandler) ListCustomFieldOptions(ctx context.Context, params ListCustomFieldOptionsParams) (r *CustomFieldOptionListResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListEpicComments implements listEpicComments operation.
//
// Get all comments on an epic.
//
// GET /epics/{epic_id}/comments
func (UnimplementedHandler) ListEpicComments(ctx context.Context, params ListEpicCommentsParams) (r *CommentsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListEpics implements listEpics operation.
//
// Get all epics with optional filtering.
//
// GET /epics
func (UnimplementedHandler) ListEpics(ctx context.Context, params ListEpicsParams) (r *EpicsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListFeatureComments implements listFeatureComments operation.
//
// Get all comments on a feature.
//
// GET /features/{feature_id}/comments
func (UnimplementedHandler) ListFeatureComments(ctx context.Context, params ListFeatureCommentsParams) (r *CommentsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListFeatureRequirements implements listFeatureRequirements operation.
//
// Get all requirements for a feature.
//
// GET /features/{feature_id}/requirements
func (UnimplementedHandler) ListFeatureRequirements(ctx context.Context, params ListFeatureRequirementsParams) (r *RequirementsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListFeatures implements listFeatures operation.
//
// Get all features with optional filtering.
//
// GET /features
func (UnimplementedHandler) ListFeatures(ctx context.Context, params ListFeaturesParams) (r *FeaturesResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListGoalComments implements listGoalComments operation.
//
// Get all comments on a goal.
//
// GET /goals/{goal_id}/comments
func (UnimplementedHandler) ListGoalComments(ctx context.Context, params ListGoalCommentsParams) (r *CommentsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListGoals implements listGoals operation.
//
// Get all goals with optional filtering.
//
// GET /goals
func (UnimplementedHandler) ListGoals(ctx context.Context, params ListGoalsParams) (r *GoalsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListIdeaComments implements listIdeaComments operation.
//
// Get all comments on an idea.
//
// GET /ideas/{idea_id}/comments
func (UnimplementedHandler) ListIdeaComments(ctx context.Context, params ListIdeaCommentsParams) (r *CommentsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListIdeas implements listIdeas operation.
//
// Get all ideas with optional filtering.
//
// GET /ideas
func (UnimplementedHandler) ListIdeas(ctx context.Context, params ListIdeasParams) (r *IdeasResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListInitiativeComments implements listInitiativeComments operation.
//
// Get all comments on an initiative.
//
// GET /initiatives/{initiative_id}/comments
func (UnimplementedHandler) ListInitiativeComments(ctx context.Context, params ListInitiativeCommentsParams) (r *CommentsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListInitiatives implements listInitiatives operation.
//
// Get all initiatives with optional filtering.
//
// GET /initiatives
func (UnimplementedHandler) ListInitiatives(ctx context.Context, params ListInitiativesParams) (r *InitiativesResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProductComments implements listProductComments operation.
//
// Get all comments in a product.
//
// GET /products/{product_id}/comments
func (UnimplementedHandler) ListProductComments(ctx context.Context, params ListProductCommentsParams) (r *CommentsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProductCustomFieldDefinitions implements listProductCustomFieldDefinitions operation.
//
// Returns custom field definitions for a specific product.
//
// GET /products/{product_id}/custom_field_definitions
func (UnimplementedHandler) ListProductCustomFieldDefinitions(ctx context.Context, params ListProductCustomFieldDefinitionsParams) (r *CustomFieldDefinitionListResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProductEpics implements listProductEpics operation.
//
// Get all epics for a product.
//
// GET /products/{product_id}/epics
func (UnimplementedHandler) ListProductEpics(ctx context.Context, params ListProductEpicsParams) (r *EpicsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProductGoals implements listProductGoals operation.
//
// Get all goals for a product.
//
// GET /products/{product_id}/goals
func (UnimplementedHandler) ListProductGoals(ctx context.Context, params ListProductGoalsParams) (r *GoalsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProductInitiatives implements listProductInitiatives operation.
//
// Get all initiatives for a product.
//
// GET /products/{product_id}/initiatives
func (UnimplementedHandler) ListProductInitiatives(ctx context.Context, params ListProductInitiativesParams) (r *InitiativesResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProductReleases implements listProductReleases operation.
//
// Get all releases for a product.
//
// GET /products/{product_id}/releases
func (UnimplementedHandler) ListProductReleases(ctx context.Context, params ListProductReleasesParams) (r *ReleasesResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProductStrategicModels implements listProductStrategicModels operation.
//
// Get all strategic models for a product.
//
// GET /products/{product_id}/strategy_models
func (UnimplementedHandler) ListProductStrategicModels(ctx context.Context, params ListProductStrategicModelsParams) (r *StrategicModelsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProductWorkflows implements listProductWorkflows operation.
//
// Get all workflows and their statuses for a product.
//
// GET /products/{product_id}/workflows
func (UnimplementedHandler) ListProductWorkflows(ctx context.Context, params ListProductWorkflowsParams) (r *WorkflowsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProducts implements listProducts operation.
//
// Get all products (workspaces) including Aha! Develop teams.
//
// GET /products
func (UnimplementedHandler) ListProducts(ctx context.Context, params ListProductsParams) (r *ProductsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListReleaseComments implements listReleaseComments operation.
//
// Get all comments on a release.
//
// GET /releases/{release_id}/comments
func (UnimplementedHandler) ListReleaseComments(ctx context.Context, params ListReleaseCommentsParams) (r *CommentsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListReleaseFeatures implements listReleaseFeatures operation.
//
// Get all features for a specific release.
//
// GET /releases/{release_id}/features
func (UnimplementedHandler) ListReleaseFeatures(ctx context.Context, params ListReleaseFeaturesParams) (r *FeaturesResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListStrategicModels implements listStrategicModels operation.
//
// Get all strategic models (canvases) with optional filtering.
//
// GET /strategy_models
func (UnimplementedHandler) ListStrategicModels(ctx context.Context, params ListStrategicModelsParams) (r *StrategicModelsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListUsers implements listUsers operation.
//
// Get all users in the account.
//
// GET /users
func (UnimplementedHandler) ListUsers(ctx context.Context, params ListUsersParams) (r *UsersResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateComment implements updateComment operation.
//
// Update an existing comment.
//
// PUT /comments/{comment_id}
func (UnimplementedHandler) UpdateComment(ctx context.Context, req *CommentUpdateRequest, params UpdateCommentParams) (r *CommentResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateEpic implements updateEpic operation.
//
// Update an existing epic.
//
// PUT /epics/{epic_id}
func (UnimplementedHandler) UpdateEpic(ctx context.Context, req *EpicUpdateRequest, params UpdateEpicParams) (r *EpicResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateFeature implements updateFeature operation.
//
// Update an existing feature.
//
// PUT /features/{feature_id}
func (UnimplementedHandler) UpdateFeature(ctx context.Context, req *FeatureUpdateRequest, params UpdateFeatureParams) (r *FeatureResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateGoal implements updateGoal operation.
//
// Update an existing goal.
//
// PUT /goals/{goal_id}
func (UnimplementedHandler) UpdateGoal(ctx context.Context, req *GoalUpdateRequest, params UpdateGoalParams) (r *GoalResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateIdea implements updateIdea operation.
//
// Update an existing idea.
//
// PUT /ideas/{idea_id}
func (UnimplementedHandler) UpdateIdea(ctx context.Context, req *IdeaUpdateRequest, params UpdateIdeaParams) (r *IdeaResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateInitiative implements updateInitiative operation.
//
// Update an existing initiative.
//
// PUT /initiatives/{initiative_id}
func (UnimplementedHandler) UpdateInitiative(ctx context.Context, req *InitiativeUpdateRequest, params UpdateInitiativeParams) (r *InitiativeResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateProduct implements updateProduct operation.
//
// Update an existing product.
//
// PUT /products/{product_id}
func (UnimplementedHandler) UpdateProduct(ctx context.Context, req *ProductUpdateRequest, params UpdateProductParams) (r *ProductResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateRelease implements updateRelease operation.
//
// Update an existing release.
//
// PUT /releases/{release_id}
func (UnimplementedHandler) UpdateRelease(ctx context.Context, req *ReleaseUpdateRequest, params UpdateReleaseParams) (r *ReleaseResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateRequirement implements updateRequirement operation.
//
// Update an existing requirement.
//
// PUT /requirements/{requirement_id}
func (UnimplementedHandler) UpdateRequirement(ctx context.Context, req *RequirementUpdateRequest, params UpdateRequirementParams) (r *RequirementResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateStrategicModel implements updateStrategicModel operation.
//
// Update an existing strategic model.
//
// PUT /strategy_models/{strategy_model_id}
func (UnimplementedHandler) UpdateStrategicModel(ctx context.Context, req *StrategicModelUpdateRequest, params UpdateStrategicModelParams) (r *StrategicModelResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateStrategicModelComponent implements updateStrategicModelComponent operation.
//
// Update a component (block) within a strategic model.
//
// PUT /strategy_models/{strategy_model_id}/components/{component_id}
func (UnimplementedHandler) UpdateStrategicModelComponent(ctx context.Context, req *StrategicModelComponentUpdateRequest, params UpdateStrategicModelComponentParams) (r *StrategicModelComponentResponse, _ error) {
	return r, ht.ErrNotImplemented
}
