// Code generated by ogen, DO NOT EDIT.
package api

type GetCommentRes interface {
	getCommentRes()
}

type GetEpicRes interface {
	getEpicRes()
}

type GetFeatureRes interface {
	getFeatureRes()
}

type GetGoalRes interface {
	getGoalRes()
}

type GetInitiativeRes interface {
	getInitiativeRes()
}

type GetRequirementRes interface {
	getRequirementRes()
}

type GetStrategicModelRes interface {
	getStrategicModelRes()
}
