// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn24AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"GET":    "Authorization",
		"PUT":    "Authorization,Content-Type",
	}
	rn47AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn50AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn52AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn30AllowedHeaders = map[string]string{
		"GET": "Authorization",
		"PUT": "Authorization,Content-Type",
	}
	rn51AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn54AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn2AllowedHeaders = map[string]string{
		"GET": "Authorization",
		"PUT": "Authorization,Content-Type",
	}
	rn3AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn53AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn5AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn56AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn32AllowedHeaders = map[string]string{
		"GET": "Authorization",
		"PUT": "Authorization,Content-Type",
	}
	rn55AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn59AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn35AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn60AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn38AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn61AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn8AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"GET":    "Authorization",
		"PUT":    "Authorization,Content-Type",
	}
	rn9AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn58AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn63AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn41AllowedHeaders = map[string]string{
		"GET": "Authorization",
		"PUT": "Authorization,Content-Type",
	}
	rn62AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn28AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn10AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn12AllowedHeaders = map[string]string{
		"GET": "Authorization",
		"PUT": "Authorization,Content-Type",
	}
	rn64AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn66AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn67AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn13AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn69AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn15AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn17AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn16AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn70AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn19AllowedHeaders = map[string]string{
		"GET": "Authorization",
		"PUT": "Authorization,Content-Type",
	}
	rn71AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn20AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn22AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn27AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"GET":    "Authorization",
		"PUT":    "Authorization,Content-Type",
	}
	rn72AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn43AllowedHeaders = map[string]string{
		"GET": "Authorization",
		"PUT": "Authorization,Content-Type",
	}
	rn75AllowedHeaders = map[string]string{
		"PUT": "Authorization,Content-Type",
	}
	rn73AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn45AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [2]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'c': // Prefix: "c"

				if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'o': // Prefix: "omments/"

					if l := len("omments/"); len(elem) >= l && elem[0:l] == "omments/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "comment_id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "DELETE":
							s.handleDeleteCommentRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handleGetCommentRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleUpdateCommentRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE,GET,PUT",
								allowedHeaders: rn24AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				case 'u': // Prefix: "ustom_field_definitions"

					if l := len("ustom_field_definitions"); len(elem) >= l && elem[0:l] == "ustom_field_definitions" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleListCustomFieldDefinitionsRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: rn47AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/options"

							if l := len("/options"); len(elem) >= l && elem[0:l] == "/options" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleListCustomFieldOptionsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn50AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				}

			case 'e': // Prefix: "epics"

				if l := len("epics"); len(elem) >= l && elem[0:l] == "epics" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListEpicsRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: rn52AllowedHeaders,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "epic_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleGetEpicRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleUpdateEpicRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,PUT",
								allowedHeaders: rn30AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/comments"

						if l := len("/comments"); len(elem) >= l && elem[0:l] == "/comments" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleListEpicCommentsRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn51AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			case 'f': // Prefix: "features"

				if l := len("features"); len(elem) >= l && elem[0:l] == "features" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListFeaturesRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: rn54AllowedHeaders,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "feature_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleGetFeatureRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleUpdateFeatureRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,PUT",
								allowedHeaders: rn2AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'c': // Prefix: "comments"

							if l := len("comments"); len(elem) >= l && elem[0:l] == "comments" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleListFeatureCommentsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "POST":
									s.handleCreateFeatureCommentRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET,POST",
										allowedHeaders: rn3AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'i': // Prefix: "ideas"

							if l := len("ideas"); len(elem) >= l && elem[0:l] == "ideas" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleListFeatureIdeasRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn53AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'r': // Prefix: "requirements"

							if l := len("requirements"); len(elem) >= l && elem[0:l] == "requirements" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleListFeatureRequirementsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "POST":
									s.handleCreateFeatureRequirementRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET,POST",
										allowedHeaders: rn5AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				}

			case 'g': // Prefix: "goals"

				if l := len("goals"); len(elem) >= l && elem[0:l] == "goals" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListGoalsRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: rn56AllowedHeaders,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "goal_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleGetGoalRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleUpdateGoalRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,PUT",
								allowedHeaders: rn32AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/comments"

						if l := len("/comments"); len(elem) >= l && elem[0:l] == "/comments" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleListGoalCommentsRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn55AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			case 'i': // Prefix: "i"

				if l := len("i"); len(elem) >= l && elem[0:l] == "i" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'd': // Prefix: "dea"

					if l := len("dea"); len(elem) >= l && elem[0:l] == "dea" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '_': // Prefix: "_"

						if l := len("_"); len(elem) >= l && elem[0:l] == "_" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'o': // Prefix: "organizations"

							if l := len("organizations"); len(elem) >= l && elem[0:l] == "organizations" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleListIdeaOrganizationsRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn59AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "idea_organization_id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleGetIdeaOrganizationRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn35AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 'u': // Prefix: "users"

							if l := len("users"); len(elem) >= l && elem[0:l] == "users" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleListIdeaUsersRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn60AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "idea_user_id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleGetIdeaUserRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn38AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						}

					case 's': // Prefix: "s"

						if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleListIdeasRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn61AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "idea_id"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[0] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								switch r.Method {
								case "DELETE":
									s.handleDeleteIdeaRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "GET":
									s.handleGetIdeaRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "PUT":
									s.handleUpdateIdeaRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "DELETE,GET,PUT",
										allowedHeaders: rn8AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'c': // Prefix: "comments"

									if l := len("comments"); len(elem) >= l && elem[0:l] == "comments" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "GET":
											s.handleListIdeaCommentsRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										case "POST":
											s.handleCreateIdeaCommentRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "GET,POST",
												allowedHeaders: rn9AllowedHeaders,
												acceptPost:     "application/json",
												acceptPatch:    "",
											})
										}

										return
									}

								case 'e': // Prefix: "endorsements"

									if l := len("endorsements"); len(elem) >= l && elem[0:l] == "endorsements" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "GET":
											s.handleListIdeaEndorsementsRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "GET",
												allowedHeaders: rn58AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "",
											})
										}

										return
									}

								}

							}

						}

					}

				case 'n': // Prefix: "nitiatives"

					if l := len("nitiatives"); len(elem) >= l && elem[0:l] == "nitiatives" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleListInitiativesRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: rn63AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "initiative_id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleGetInitiativeRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "PUT":
								s.handleUpdateInitiativeRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET,PUT",
									allowedHeaders: rn41AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/comments"

							if l := len("/comments"); len(elem) >= l && elem[0:l] == "/comments" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleListInitiativeCommentsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn62AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				}

			case 'm': // Prefix: "me"

				if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetCurrentUserRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: rn28AllowedHeaders,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'p': // Prefix: "products"

				if l := len("products"); len(elem) >= l && elem[0:l] == "products" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListProductsRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreateProductRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn10AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "product_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleGetProductRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleUpdateProductRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,PUT",
								allowedHeaders: rn12AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'c': // Prefix: "c"

							if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'o': // Prefix: "omments"

								if l := len("omments"); len(elem) >= l && elem[0:l] == "omments" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleListProductCommentsRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn64AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							case 'u': // Prefix: "ustom_field_definitions"

								if l := len("ustom_field_definitions"); len(elem) >= l && elem[0:l] == "ustom_field_definitions" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleListProductCustomFieldDefinitionsRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn66AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 'e': // Prefix: "epics"

							if l := len("epics"); len(elem) >= l && elem[0:l] == "epics" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleListProductEpicsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn67AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'g': // Prefix: "goals"

							if l := len("goals"); len(elem) >= l && elem[0:l] == "goals" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleListProductGoalsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "POST":
									s.handleCreateProductGoalRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET,POST",
										allowedHeaders: rn13AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'i': // Prefix: "i"

							if l := len("i"); len(elem) >= l && elem[0:l] == "i" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'd': // Prefix: "dea_categories"

								if l := len("dea_categories"); len(elem) >= l && elem[0:l] == "dea_categories" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleListProductIdeaCategoriesRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn69AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							case 'n': // Prefix: "nitiatives"

								if l := len("nitiatives"); len(elem) >= l && elem[0:l] == "nitiatives" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleListProductInitiativesRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									case "POST":
										s.handleCreateProductInitiativeRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET,POST",
											allowedHeaders: rn15AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 'r': // Prefix: "releases"

							if l := len("releases"); len(elem) >= l && elem[0:l] == "releases" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleListProductReleasesRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "POST":
									s.handleCreateReleaseRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET,POST",
										allowedHeaders: rn17AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						case 's': // Prefix: "strategy_models"

							if l := len("strategy_models"); len(elem) >= l && elem[0:l] == "strategy_models" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleListProductStrategicModelsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "POST":
									s.handleCreateProductStrategicModelRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET,POST",
										allowedHeaders: rn16AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'w': // Prefix: "workflows"

							if l := len("workflows"); len(elem) >= l && elem[0:l] == "workflows" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleListProductWorkflowsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn70AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				}

			case 'r': // Prefix: "re"

				if l := len("re"); len(elem) >= l && elem[0:l] == "re" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'l': // Prefix: "leases/"

					if l := len("leases/"); len(elem) >= l && elem[0:l] == "leases/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "release_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleGetReleaseRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleUpdateReleaseRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,PUT",
								allowedHeaders: rn19AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'c': // Prefix: "comments"

							if l := len("comments"); len(elem) >= l && elem[0:l] == "comments" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleListReleaseCommentsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn71AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'e': // Prefix: "epics"

							if l := len("epics"); len(elem) >= l && elem[0:l] == "epics" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleCreateReleaseEpicRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn20AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'f': // Prefix: "features"

							if l := len("features"); len(elem) >= l && elem[0:l] == "features" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleListReleaseFeaturesRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "POST":
									s.handleCreateReleaseFeatureRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET,POST",
										allowedHeaders: rn22AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				case 'q': // Prefix: "quirements/"

					if l := len("quirements/"); len(elem) >= l && elem[0:l] == "quirements/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "requirement_id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "DELETE":
							s.handleDeleteRequirementRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handleGetRequirementRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleUpdateRequirementRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE,GET,PUT",
								allowedHeaders: rn27AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 's': // Prefix: "strategy_models"

				if l := len("strategy_models"); len(elem) >= l && elem[0:l] == "strategy_models" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListStrategicModelsRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: rn72AllowedHeaders,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "strategy_model_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleGetStrategicModelRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleUpdateStrategicModelRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,PUT",
								allowedHeaders: rn43AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/components/"

						if l := len("/components/"); len(elem) >= l && elem[0:l] == "/components/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "component_id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "PUT":
								s.handleUpdateStrategicModelComponentRequest([2]string{
									args[0],
									args[1],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "PUT",
									allowedHeaders: rn75AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			case 'u': // Prefix: "users"

				if l := len("users"); len(elem) >= l && elem[0:l] == "users" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListUsersRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: rn73AllowedHeaders,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "user_id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleGetUserRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: rn45AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [2]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'c': // Prefix: "c"

				if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'o': // Prefix: "omments/"

					if l := len("omments/"); len(elem) >= l && elem[0:l] == "omments/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "comment_id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "DELETE":
							r.name = DeleteCommentOperation
							r.summary = "Delete comment"
							r.operationID = "deleteComment"
							r.operationGroup = ""
							r.pathPattern = "/comments/{comment_id}"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = GetCommentOperation
							r.summary = "Get comment"
							r.operationID = "getComment"
							r.operationGroup = ""
							r.pathPattern = "/comments/{comment_id}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = UpdateCommentOperation
							r.summary = "Update comment"
							r.operationID = "updateComment"
							r.operationGroup = ""
							r.pathPattern = "/comments/{comment_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				case 'u': // Prefix: "ustom_field_definitions"

					if l := len("ustom_field_definitions"); len(elem) >= l && elem[0:l] == "ustom_field_definitions" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = ListCustomFieldDefinitionsOperation
							r.summary = "List all custom field definitions"
							r.operationID = "listCustomFieldDefinitions"
							r.operationGroup = ""
							r.pathPattern = "/custom_field_definitions"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/options"

							if l := len("/options"); len(elem) >= l && elem[0:l] == "/options" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ListCustomFieldOptionsOperation
									r.summary = "List options for a custom field"
									r.operationID = "listCustomFieldOptions"
									r.operationGroup = ""
									r.pathPattern = "/custom_field_definitions/{id}/options"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			case 'e': // Prefix: "epics"

				if l := len("epics"); len(elem) >= l && elem[0:l] == "epics" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListEpicsOperation
						r.summary = "List epics"
						r.operationID = "listEpics"
						r.operationGroup = ""
						r.pathPattern = "/epics"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "epic_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = GetEpicOperation
							r.summary = "Get epic"
							r.operationID = "getEpic"
							r.operationGroup = ""
							r.pathPattern = "/epics/{epic_id}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = UpdateEpicOperation
							r.summary = "Update epic"
							r.operationID = "updateEpic"
							r.operationGroup = ""
							r.pathPattern = "/epics/{epic_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/comments"

						if l := len("/comments"); len(elem) >= l && elem[0:l] == "/comments" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = ListEpicCommentsOperation
								r.summary = "List comments on an epic"
								r.operationID = "listEpicComments"
								r.operationGroup = ""
								r.pathPattern = "/epics/{epic_id}/comments"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'f': // Prefix: "features"

				if l := len("features"); len(elem) >= l && elem[0:l] == "features" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListFeaturesOperation
						r.summary = "List features"
						r.operationID = "listFeatures"
						r.operationGroup = ""
						r.pathPattern = "/features"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "feature_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = GetFeatureOperation
							r.summary = "Get feature"
							r.operationID = "getFeature"
							r.operationGroup = ""
							r.pathPattern = "/features/{feature_id}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = UpdateFeatureOperation
							r.summary = "Update feature"
							r.operationID = "updateFeature"
							r.operationGroup = ""
							r.pathPattern = "/features/{feature_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'c': // Prefix: "comments"

							if l := len("comments"); len(elem) >= l && elem[0:l] == "comments" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ListFeatureCommentsOperation
									r.summary = "List comments on a feature"
									r.operationID = "listFeatureComments"
									r.operationGroup = ""
									r.pathPattern = "/features/{feature_id}/comments"
									r.args = args
									r.count = 1
									return r, true
								case "POST":
									r.name = CreateFeatureCommentOperation
									r.summary = "Create comment on a feature"
									r.operationID = "createFeatureComment"
									r.operationGroup = ""
									r.pathPattern = "/features/{feature_id}/comments"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'i': // Prefix: "ideas"

							if l := len("ideas"); len(elem) >= l && elem[0:l] == "ideas" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ListFeatureIdeasOperation
									r.summary = "List ideas linked to a feature"
									r.operationID = "listFeatureIdeas"
									r.operationGroup = ""
									r.pathPattern = "/features/{feature_id}/ideas"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'r': // Prefix: "requirements"

							if l := len("requirements"); len(elem) >= l && elem[0:l] == "requirements" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ListFeatureRequirementsOperation
									r.summary = "List feature requirements"
									r.operationID = "listFeatureRequirements"
									r.operationGroup = ""
									r.pathPattern = "/features/{feature_id}/requirements"
									r.args = args
									r.count = 1
									return r, true
								case "POST":
									r.name = CreateFeatureRequirementOperation
									r.summary = "Create requirement for feature"
									r.operationID = "createFeatureRequirement"
									r.operationGroup = ""
									r.pathPattern = "/features/{feature_id}/requirements"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			case 'g': // Prefix: "goals"

				if l := len("goals"); len(elem) >= l && elem[0:l] == "goals" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListGoalsOperation
						r.summary = "List goals"
						r.operationID = "listGoals"
						r.operationGroup = ""
						r.pathPattern = "/goals"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "goal_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = GetGoalOperation
							r.summary = "Get goal"
							r.operationID = "getGoal"
							r.operationGroup = ""
							r.pathPattern = "/goals/{goal_id}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = UpdateGoalOperation
							r.summary = "Update goal"
							r.operationID = "updateGoal"
							r.operationGroup = ""
							r.pathPattern = "/goals/{goal_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/comments"

						if l := len("/comments"); len(elem) >= l && elem[0:l] == "/comments" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = ListGoalCommentsOperation
								r.summary = "List comments on a goal"
								r.operationID = "listGoalComments"
								r.operationGroup = ""
								r.pathPattern = "/goals/{goal_id}/comments"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'i': // Prefix: "i"

				if l := len("i"); len(elem) >= l && elem[0:l] == "i" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'd': // Prefix: "dea"

					if l := len("dea"); len(elem) >= l && elem[0:l] == "dea" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '_': // Prefix: "_"

						if l := len("_"); len(elem) >= l && elem[0:l] == "_" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'o': // Prefix: "organizations"

							if l := len("organizations"); len(elem) >= l && elem[0:l] == "organizations" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = ListIdeaOrganizationsOperation
									r.summary = "List idea organizations (customer/account records)"
									r.operationID = "listIdeaOrganizations"
									r.operationGroup = ""
									r.pathPattern = "/idea_organizations"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "idea_organization_id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = GetIdeaOrganizationOperation
										r.summary = "Get an idea organization by ID"
										r.operationID = "getIdeaOrganization"
										r.operationGroup = ""
										r.pathPattern = "/idea_organizations/{idea_organization_id}"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						case 'u': // Prefix: "users"

							if l := len("users"); len(elem) >= l && elem[0:l] == "users" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = ListIdeaUsersOperation
									r.summary = "List idea users (voter identities)"
									r.operationID = "listIdeaUsers"
									r.operationGroup = ""
									r.pathPattern = "/idea_users"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "idea_user_id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = GetIdeaUserOperation
										r.summary = "Get an idea user by ID"
										r.operationID = "getIdeaUser"
										r.operationGroup = ""
										r.pathPattern = "/idea_users/{idea_user_id}"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						}

					case 's': // Prefix: "s"

						if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = ListIdeasOperation
								r.summary = "List ideas"
								r.operationID = "listIdeas"
								r.operationGroup = ""
								r.pathPattern = "/ideas"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "idea_id"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[0] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								switch method {
								case "DELETE":
									r.name = DeleteIdeaOperation
									r.summary = "Delete idea"
									r.operationID = "deleteIdea"
									r.operationGroup = ""
									r.pathPattern = "/ideas/{idea_id}"
									r.args = args
									r.count = 1
									return r, true
								case "GET":
									r.name = GetIdeaOperation
									r.summary = "Get idea"
									r.operationID = "getIdea"
									r.operationGroup = ""
									r.pathPattern = "/ideas/{idea_id}"
									r.args = args
									r.count = 1
									return r, true
								case "PUT":
									r.name = UpdateIdeaOperation
									r.summary = "Update idea"
									r.operationID = "updateIdea"
									r.operationGroup = ""
									r.pathPattern = "/ideas/{idea_id}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'c': // Prefix: "comments"

									if l := len("comments"); len(elem) >= l && elem[0:l] == "comments" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "GET":
											r.name = ListIdeaCommentsOperation
											r.summary = "List comments on an idea"
											r.operationID = "listIdeaComments"
											r.operationGroup = ""
											r.pathPattern = "/ideas/{idea_id}/comments"
											r.args = args
											r.count = 1
											return r, true
										case "POST":
											r.name = CreateIdeaCommentOperation
											r.summary = "Create internal comment on an idea"
											r.operationID = "createIdeaComment"
											r.operationGroup = ""
											r.pathPattern = "/ideas/{idea_id}/comments"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

								case 'e': // Prefix: "endorsements"

									if l := len("endorsements"); len(elem) >= l && elem[0:l] == "endorsements" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "GET":
											r.name = ListIdeaEndorsementsOperation
											r.summary = "List endorsements (votes) on an idea"
											r.operationID = "listIdeaEndorsements"
											r.operationGroup = ""
											r.pathPattern = "/ideas/{idea_id}/endorsements"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

								}

							}

						}

					}

				case 'n': // Prefix: "nitiatives"

					if l := len("nitiatives"); len(elem) >= l && elem[0:l] == "nitiatives" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = ListInitiativesOperation
							r.summary = "List initiatives"
							r.operationID = "listInitiatives"
							r.operationGroup = ""
							r.pathPattern = "/initiatives"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "initiative_id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = GetInitiativeOperation
								r.summary = "Get initiative"
								r.operationID = "getInitiative"
								r.operationGroup = ""
								r.pathPattern = "/initiatives/{initiative_id}"
								r.args = args
								r.count = 1
								return r, true
							case "PUT":
								r.name = UpdateInitiativeOperation
								r.summary = "Update initiative"
								r.operationID = "updateInitiative"
								r.operationGroup = ""
								r.pathPattern = "/initiatives/{initiative_id}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/comments"

							if l := len("/comments"); len(elem) >= l && elem[0:l] == "/comments" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ListInitiativeCommentsOperation
									r.summary = "List comments on an initiative"
									r.operationID = "listInitiativeComments"
									r.operationGroup = ""
									r.pathPattern = "/initiatives/{initiative_id}/comments"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			case 'm': // Prefix: "me"

				if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetCurrentUserOperation
						r.summary = "Get current user"
						r.operationID = "getCurrentUser"
						r.operationGroup = ""
						r.pathPattern = "/me"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'p': // Prefix: "products"

				if l := len("products"); len(elem) >= l && elem[0:l] == "products" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListProductsOperation
						r.summary = "List products"
						r.operationID = "listProducts"
						r.operationGroup = ""
						r.pathPattern = "/products"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreateProductOperation
						r.summary = "Create product"
						r.operationID = "createProduct"
						r.operationGroup = ""
						r.pathPattern = "/products"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "product_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = GetProductOperation
							r.summary = "Get product"
							r.operationID = "getProduct"
							r.operationGroup = ""
							r.pathPattern = "/products/{product_id}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = UpdateProductOperation
							r.summary = "Update product"
							r.operationID = "updateProduct"
							r.operationGroup = ""
							r.pathPattern = "/products/{product_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'c': // Prefix: "c"

							if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'o': // Prefix: "omments"

								if l := len("omments"); len(elem) >= l && elem[0:l] == "omments" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = ListProductCommentsOperation
										r.summary = "List comments in a product"
										r.operationID = "listProductComments"
										r.operationGroup = ""
										r.pathPattern = "/products/{product_id}/comments"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 'u': // Prefix: "ustom_field_definitions"

								if l := len("ustom_field_definitions"); len(elem) >= l && elem[0:l] == "ustom_field_definitions" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = ListProductCustomFieldDefinitionsOperation
										r.summary = "List custom field definitions for a product"
										r.operationID = "listProductCustomFieldDefinitions"
										r.operationGroup = ""
										r.pathPattern = "/products/{product_id}/custom_field_definitions"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						case 'e': // Prefix: "epics"

							if l := len("epics"); len(elem) >= l && elem[0:l] == "epics" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ListProductEpicsOperation
									r.summary = "List product epics"
									r.operationID = "listProductEpics"
									r.operationGroup = ""
									r.pathPattern = "/products/{product_id}/epics"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'g': // Prefix: "goals"

							if l := len("goals"); len(elem) >= l && elem[0:l] == "goals" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ListProductGoalsOperation
									r.summary = "List product goals"
									r.operationID = "listProductGoals"
									r.operationGroup = ""
									r.pathPattern = "/products/{product_id}/goals"
									r.args = args
									r.count = 1
									return r, true
								case "POST":
									r.name = CreateProductGoalOperation
									r.summary = "Create goal in product"
									r.operationID = "createProductGoal"
									r.operationGroup = ""
									r.pathPattern = "/products/{product_id}/goals"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'i': // Prefix: "i"

							if l := len("i"); len(elem) >= l && elem[0:l] == "i" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'd': // Prefix: "dea_categories"

								if l := len("dea_categories"); len(elem) >= l && elem[0:l] == "dea_categories" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = ListProductIdeaCategoriesOperation
										r.summary = "List idea categories"
										r.operationID = "listProductIdeaCategories"
										r.operationGroup = ""
										r.pathPattern = "/products/{product_id}/idea_categories"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 'n': // Prefix: "nitiatives"

								if l := len("nitiatives"); len(elem) >= l && elem[0:l] == "nitiatives" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = ListProductInitiativesOperation
										r.summary = "List product initiatives"
										r.operationID = "listProductInitiatives"
										r.operationGroup = ""
										r.pathPattern = "/products/{product_id}/initiatives"
										r.args = args
										r.count = 1
										return r, true
									case "POST":
										r.name = CreateProductInitiativeOperation
										r.summary = "Create initiative in product"
										r.operationID = "createProductInitiative"
										r.operationGroup = ""
										r.pathPattern = "/products/{product_id}/initiatives"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						case 'r': // Prefix: "releases"

							if l := len("releases"); len(elem) >= l && elem[0:l] == "releases" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ListProductReleasesOperation
									r.summary = "List product releases"
									r.operationID = "listProductReleases"
									r.operationGroup = ""
									r.pathPattern = "/products/{product_id}/releases"
									r.args = args
									r.count = 1
									return r, true
								case "POST":
									r.name = CreateReleaseOperation
									r.summary = "Create release"
									r.operationID = "createRelease"
									r.operationGroup = ""
									r.pathPattern = "/products/{product_id}/releases"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 's': // Prefix: "strategy_models"

							if l := len("strategy_models"); len(elem) >= l && elem[0:l] == "strategy_models" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ListProductStrategicModelsOperation
									r.summary = "List product strategic models"
									r.operationID = "listProductStrategicModels"
									r.operationGroup = ""
									r.pathPattern = "/products/{product_id}/strategy_models"
									r.args = args
									r.count = 1
									return r, true
								case "POST":
									r.name = CreateProductStrategicModelOperation
									r.summary = "Create strategic model in product"
									r.operationID = "createProductStrategicModel"
									r.operationGroup = ""
									r.pathPattern = "/products/{product_id}/strategy_models"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'w': // Prefix: "workflows"

							if l := len("workflows"); len(elem) >= l && elem[0:l] == "workflows" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ListProductWorkflowsOperation
									r.summary = "List product workflows"
									r.operationID = "listProductWorkflows"
									r.operationGroup = ""
									r.pathPattern = "/products/{product_id}/workflows"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			case 'r': // Prefix: "re"

				if l := len("re"); len(elem) >= l && elem[0:l] == "re" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'l': // Prefix: "leases/"

					if l := len("leases/"); len(elem) >= l && elem[0:l] == "leases/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "release_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = GetReleaseOperation
							r.summary = "Get release"
							r.operationID = "getRelease"
							r.operationGroup = ""
							r.pathPattern = "/releases/{release_id}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = UpdateReleaseOperation
							r.summary = "Update release"
							r.operationID = "updateRelease"
							r.operationGroup = ""
							r.pathPattern = "/releases/{release_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'c': // Prefix: "comments"

							if l := len("comments"); len(elem) >= l && elem[0:l] == "comments" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ListReleaseCommentsOperation
									r.summary = "List comments on a release"
									r.operationID = "listReleaseComments"
									r.operationGroup = ""
									r.pathPattern = "/releases/{release_id}/comments"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'e': // Prefix: "epics"

							if l := len("epics"); len(elem) >= l && elem[0:l] == "epics" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = CreateReleaseEpicOperation
									r.summary = "Create epic in release"
									r.operationID = "createReleaseEpic"
									r.operationGroup = ""
									r.pathPattern = "/releases/{release_id}/epics"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'f': // Prefix: "features"

							if l := len("features"); len(elem) >= l && elem[0:l] == "features" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ListReleaseFeaturesOperation
									r.summary = "List features in release"
									r.operationID = "listReleaseFeatures"
									r.operationGroup = ""
									r.pathPattern = "/releases/{release_id}/features"
									r.args = args
									r.count = 1
									return r, true
								case "POST":
									r.name = CreateReleaseFeatureOperation
									r.summary = "Create feature in release"
									r.operationID = "createReleaseFeature"
									r.operationGroup = ""
									r.pathPattern = "/releases/{release_id}/features"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				case 'q': // Prefix: "quirements/"

					if l := len("quirements/"); len(elem) >= l && elem[0:l] == "quirements/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "requirement_id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "DELETE":
							r.name = DeleteRequirementOperation
							r.summary = "Delete requirement"
							r.operationID = "deleteRequirement"
							r.operationGroup = ""
							r.pathPattern = "/requirements/{requirement_id}"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = GetRequirementOperation
							r.summary = "Get requirement"
							r.operationID = "getRequirement"
							r.operationGroup = ""
							r.pathPattern = "/requirements/{requirement_id}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = UpdateRequirementOperation
							r.summary = "Update requirement"
							r.operationID = "updateRequirement"
							r.operationGroup = ""
							r.pathPattern = "/requirements/{requirement_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			case 's': // Prefix: "strategy_models"

				if l := len("strategy_models"); len(elem) >= l && elem[0:l] == "strategy_models" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListStrategicModelsOperation
						r.summary = "List strategic models"
						r.operationID = "listStrategicModels"
						r.operationGroup = ""
						r.pathPattern = "/strategy_models"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "strategy_model_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = GetStrategicModelOperation
							r.summary = "Get strategic model"
							r.operationID = "getStrategicModel"
							r.operationGroup = ""
							r.pathPattern = "/strategy_models/{strategy_model_id}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = UpdateStrategicModelOperation
							r.summary = "Update strategic model"
							r.operationID = "updateStrategicModel"
							r.operationGroup = ""
							r.pathPattern = "/strategy_models/{strategy_model_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/components/"

						if l := len("/components/"); len(elem) >= l && elem[0:l] == "/components/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "component_id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "PUT":
								r.name = UpdateStrategicModelComponentOperation
								r.summary = "Update strategic model component"
								r.operationID = "updateStrategicModelComponent"
								r.operationGroup = ""
								r.pathPattern = "/strategy_models/{strategy_model_id}/components/{component_id}"
								r.args = args
								r.count = 2
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'u': // Prefix: "users"

				if l := len("users"); len(elem) >= l && elem[0:l] == "users" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListUsersOperation
						r.summary = "List users"
						r.operationID = "listUsers"
						r.operationGroup = ""
						r.pathPattern = "/users"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "user_id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = GetUserOperation
							r.summary = "Get user"
							r.operationID = "getUser"
							r.operationGroup = ""
							r.pathPattern = "/users/{user_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			}

		}
	}
	return r, false
}
