// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateFeatureComment implements createFeatureComment operation.
	//
	// Create a new comment on a feature.
	//
	// POST /features/{feature_id}/comments
	CreateFeatureComment(ctx context.Context, req *CommentCreateRequest, params CreateFeatureCommentParams) (*CommentResponse, error)
	// CreateFeatureRequirement implements createFeatureRequirement operation.
	//
	// Create a new requirement for a feature.
	//
	// POST /features/{feature_id}/requirements
	CreateFeatureRequirement(ctx context.Context, req *RequirementCreateRequest, params CreateFeatureRequirementParams) (*RequirementResponse, error)
	// CreateIdeaComment implements createIdeaComment operation.
	//
	// Create a new internal comment on an idea.
	//
	// POST /ideas/{idea_id}/comments
	CreateIdeaComment(ctx context.Context, req *CommentCreateRequest, params CreateIdeaCommentParams) (*CommentResponse, error)
	// CreateProduct implements createProduct operation.
	//
	// Create a new product or product line.
	//
	// POST /products
	CreateProduct(ctx context.Context, req *ProductCreateRequest) (*ProductResponse, error)
	// CreateProductGoal implements createProductGoal operation.
	//
	// Create a new goal in a product.
	//
	// POST /products/{product_id}/goals
	CreateProductGoal(ctx context.Context, req *GoalCreateRequest, params CreateProductGoalParams) (*GoalResponse, error)
	// CreateProductInitiative implements createProductInitiative operation.
	//
	// Create a new initiative in a product.
	//
	// POST /products/{product_id}/initiatives
	CreateProductInitiative(ctx context.Context, req *InitiativeCreateRequest, params CreateProductInitiativeParams) (*InitiativeResponse, error)
	// CreateProductStrategicModel implements createProductStrategicModel operation.
	//
	// Create a new strategic model in a product.
	//
	// POST /products/{product_id}/strategy_models
	CreateProductStrategicModel(ctx context.Context, req *StrategicModelCreateRequest, params CreateProductStrategicModelParams) (*StrategicModelResponse, error)
	// CreateReleaseEpic implements createReleaseEpic operation.
	//
	// Create a new epic in a release.
	//
	// POST /releases/{release_id}/epics
	CreateReleaseEpic(ctx context.Context, req *EpicCreateRequest, params CreateReleaseEpicParams) (*EpicResponse, error)
	// CreateReleaseFeature implements createReleaseFeature operation.
	//
	// Create a new feature in a release.
	//
	// POST /releases/{release_id}/features
	CreateReleaseFeature(ctx context.Context, req *FeatureCreateRequest, params CreateReleaseFeatureParams) (*FeatureResponse, error)
	// DeleteComment implements deleteComment operation.
	//
	// Delete a comment.
	//
	// DELETE /comments/{comment_id}
	DeleteComment(ctx context.Context, params DeleteCommentParams) error
	// DeleteRequirement implements deleteRequirement operation.
	//
	// Delete a requirement.
	//
	// DELETE /requirements/{requirement_id}
	DeleteRequirement(ctx context.Context, params DeleteRequirementParams) error
	// GetComment implements getComment operation.
	//
	// Get a specific comment by ID.
	//
	// GET /comments/{comment_id}
	GetComment(ctx context.Context, params GetCommentParams) (GetCommentRes, error)
	// GetCurrentUser implements getCurrentUser operation.
	//
	// Get the currently authenticated user.
	//
	// GET /me
	GetCurrentUser(ctx context.Context) (*UserResponse, error)
	// GetEpic implements getEpic operation.
	//
	// Get a specific epic by ID or reference number.
	//
	// GET /epics/{epic_id}
	GetEpic(ctx context.Context, params GetEpicParams) (GetEpicRes, error)
	// GetFeature implements getFeature operation.
	//
	// Get a specific feature by ID or reference number.
	//
	// GET /features/{feature_id}
	GetFeature(ctx context.Context, params GetFeatureParams) (GetFeatureRes, error)
	// GetGoal implements getGoal operation.
	//
	// Get a specific goal by ID or reference number.
	//
	// GET /goals/{goal_id}
	GetGoal(ctx context.Context, params GetGoalParams) (GetGoalRes, error)
	// GetIdea implements getIdea operation.
	//
	// Get a specific idea by ID.
	//
	// GET /ideas/{idea_id}
	GetIdea(ctx context.Context, params GetIdeaParams) (*IdeaResponse, error)
	// GetInitiative implements getInitiative operation.
	//
	// Get a specific initiative by ID or reference number.
	//
	// GET /initiatives/{initiative_id}
	GetInitiative(ctx context.Context, params GetInitiativeParams) (GetInitiativeRes, error)
	// GetProduct implements getProduct operation.
	//
	// Get a specific product by ID.
	//
	// GET /products/{product_id}
	GetProduct(ctx context.Context, params GetProductParams) (*ProductResponse, error)
	// GetRelease implements getRelease operation.
	//
	// Get a specific release by ID.
	//
	// GET /releases/{release_id}
	GetRelease(ctx context.Context, params GetReleaseParams) (*ReleaseResponse, error)
	// GetRequirement implements getRequirement operation.
	//
	// Get a specific requirement by ID or reference number.
	//
	// GET /requirements/{requirement_id}
	GetRequirement(ctx context.Context, params GetRequirementParams) (GetRequirementRes, error)
	// GetStrategicModel implements getStrategicModel operation.
	//
	// Get a specific strategic model by ID or reference number.
	//
	// GET /strategy_models/{strategy_model_id}
	GetStrategicModel(ctx context.Context, params GetStrategicModelParams) (GetStrategicModelRes, error)
	// GetUser implements getUser operation.
	//
	// Get a specific user by ID.
	//
	// GET /users/{user_id}
	GetUser(ctx context.Context, params GetUserParams) (*UserResponse, error)
	// ListEpicComments implements listEpicComments operation.
	//
	// Get all comments on an epic.
	//
	// GET /epics/{epic_id}/comments
	ListEpicComments(ctx context.Context, params ListEpicCommentsParams) (*CommentsResponse, error)
	// ListEpics implements listEpics operation.
	//
	// Get all epics with optional filtering.
	//
	// GET /epics
	ListEpics(ctx context.Context, params ListEpicsParams) (*EpicsResponse, error)
	// ListFeatureComments implements listFeatureComments operation.
	//
	// Get all comments on a feature.
	//
	// GET /features/{feature_id}/comments
	ListFeatureComments(ctx context.Context, params ListFeatureCommentsParams) (*CommentsResponse, error)
	// ListFeatureRequirements implements listFeatureRequirements operation.
	//
	// Get all requirements for a feature.
	//
	// GET /features/{feature_id}/requirements
	ListFeatureRequirements(ctx context.Context, params ListFeatureRequirementsParams) (*RequirementsResponse, error)
	// ListFeatures implements listFeatures operation.
	//
	// Get all features with optional filtering.
	//
	// GET /features
	ListFeatures(ctx context.Context, params ListFeaturesParams) (*FeaturesResponse, error)
	// ListGoalComments implements listGoalComments operation.
	//
	// Get all comments on a goal.
	//
	// GET /goals/{goal_id}/comments
	ListGoalComments(ctx context.Context, params ListGoalCommentsParams) (*CommentsResponse, error)
	// ListGoals implements listGoals operation.
	//
	// Get all goals with optional filtering.
	//
	// GET /goals
	ListGoals(ctx context.Context, params ListGoalsParams) (*GoalsResponse, error)
	// ListIdeaComments implements listIdeaComments operation.
	//
	// Get all comments on an idea.
	//
	// GET /ideas/{idea_id}/comments
	ListIdeaComments(ctx context.Context, params ListIdeaCommentsParams) (*CommentsResponse, error)
	// ListIdeas implements listIdeas operation.
	//
	// Get all ideas with optional filtering.
	//
	// GET /ideas
	ListIdeas(ctx context.Context, params ListIdeasParams) (*IdeasResponse, error)
	// ListInitiativeComments implements listInitiativeComments operation.
	//
	// Get all comments on an initiative.
	//
	// GET /initiatives/{initiative_id}/comments
	ListInitiativeComments(ctx context.Context, params ListInitiativeCommentsParams) (*CommentsResponse, error)
	// ListInitiatives implements listInitiatives operation.
	//
	// Get all initiatives with optional filtering.
	//
	// GET /initiatives
	ListInitiatives(ctx context.Context, params ListInitiativesParams) (*InitiativesResponse, error)
	// ListProductComments implements listProductComments operation.
	//
	// Get all comments in a product.
	//
	// GET /products/{product_id}/comments
	ListProductComments(ctx context.Context, params ListProductCommentsParams) (*CommentsResponse, error)
	// ListProductEpics implements listProductEpics operation.
	//
	// Get all epics for a product.
	//
	// GET /products/{product_id}/epics
	ListProductEpics(ctx context.Context, params ListProductEpicsParams) (*EpicsResponse, error)
	// ListProductGoals implements listProductGoals operation.
	//
	// Get all goals for a product.
	//
	// GET /products/{product_id}/goals
	ListProductGoals(ctx context.Context, params ListProductGoalsParams) (*GoalsResponse, error)
	// ListProductInitiatives implements listProductInitiatives operation.
	//
	// Get all initiatives for a product.
	//
	// GET /products/{product_id}/initiatives
	ListProductInitiatives(ctx context.Context, params ListProductInitiativesParams) (*InitiativesResponse, error)
	// ListProductReleases implements listProductReleases operation.
	//
	// Get all releases for a product.
	//
	// GET /products/{product_id}/releases
	ListProductReleases(ctx context.Context, params ListProductReleasesParams) (*ReleasesResponse, error)
	// ListProductStrategicModels implements listProductStrategicModels operation.
	//
	// Get all strategic models for a product.
	//
	// GET /products/{product_id}/strategy_models
	ListProductStrategicModels(ctx context.Context, params ListProductStrategicModelsParams) (*StrategicModelsResponse, error)
	// ListProductWorkflows implements listProductWorkflows operation.
	//
	// Get all workflows and their statuses for a product.
	//
	// GET /products/{product_id}/workflows
	ListProductWorkflows(ctx context.Context, params ListProductWorkflowsParams) (*WorkflowsResponse, error)
	// ListProducts implements listProducts operation.
	//
	// Get all products (workspaces) including Aha! Develop teams.
	//
	// GET /products
	ListProducts(ctx context.Context, params ListProductsParams) (*ProductsResponse, error)
	// ListReleaseComments implements listReleaseComments operation.
	//
	// Get all comments on a release.
	//
	// GET /releases/{release_id}/comments
	ListReleaseComments(ctx context.Context, params ListReleaseCommentsParams) (*CommentsResponse, error)
	// ListReleaseFeatures implements listReleaseFeatures operation.
	//
	// Get all features for a specific release.
	//
	// GET /releases/{release_id}/features
	ListReleaseFeatures(ctx context.Context, params ListReleaseFeaturesParams) (*FeaturesResponse, error)
	// ListStrategicModels implements listStrategicModels operation.
	//
	// Get all strategic models (canvases) with optional filtering.
	//
	// GET /strategy_models
	ListStrategicModels(ctx context.Context, params ListStrategicModelsParams) (*StrategicModelsResponse, error)
	// ListUsers implements listUsers operation.
	//
	// Get all users in the account.
	//
	// GET /users
	ListUsers(ctx context.Context, params ListUsersParams) (*UsersResponse, error)
	// UpdateComment implements updateComment operation.
	//
	// Update an existing comment.
	//
	// PUT /comments/{comment_id}
	UpdateComment(ctx context.Context, req *CommentUpdateRequest, params UpdateCommentParams) (*CommentResponse, error)
	// UpdateEpic implements updateEpic operation.
	//
	// Update an existing epic.
	//
	// PUT /epics/{epic_id}
	UpdateEpic(ctx context.Context, req *EpicUpdateRequest, params UpdateEpicParams) (*EpicResponse, error)
	// UpdateFeature implements updateFeature operation.
	//
	// Update an existing feature.
	//
	// PUT /features/{feature_id}
	UpdateFeature(ctx context.Context, req *FeatureUpdateRequest, params UpdateFeatureParams) (*FeatureResponse, error)
	// UpdateGoal implements updateGoal operation.
	//
	// Update an existing goal.
	//
	// PUT /goals/{goal_id}
	UpdateGoal(ctx context.Context, req *GoalUpdateRequest, params UpdateGoalParams) (*GoalResponse, error)
	// UpdateInitiative implements updateInitiative operation.
	//
	// Update an existing initiative.
	//
	// PUT /initiatives/{initiative_id}
	UpdateInitiative(ctx context.Context, req *InitiativeUpdateRequest, params UpdateInitiativeParams) (*InitiativeResponse, error)
	// UpdateProduct implements updateProduct operation.
	//
	// Update an existing product.
	//
	// PUT /products/{product_id}
	UpdateProduct(ctx context.Context, req *ProductUpdateRequest, params UpdateProductParams) (*ProductResponse, error)
	// UpdateRelease implements updateRelease operation.
	//
	// Update an existing release.
	//
	// PUT /releases/{release_id}
	UpdateRelease(ctx context.Context, req *ReleaseUpdateRequest, params UpdateReleaseParams) (*ReleaseResponse, error)
	// UpdateRequirement implements updateRequirement operation.
	//
	// Update an existing requirement.
	//
	// PUT /requirements/{requirement_id}
	UpdateRequirement(ctx context.Context, req *RequirementUpdateRequest, params UpdateRequirementParams) (*RequirementResponse, error)
	// UpdateStrategicModel implements updateStrategicModel operation.
	//
	// Update an existing strategic model.
	//
	// PUT /strategy_models/{strategy_model_id}
	UpdateStrategicModel(ctx context.Context, req *StrategicModelUpdateRequest, params UpdateStrategicModelParams) (*StrategicModelResponse, error)
	// UpdateStrategicModelComponent implements updateStrategicModelComponent operation.
	//
	// Update a component (block) within a strategic model.
	//
	// PUT /strategy_models/{strategy_model_id}/components/{component_id}
	UpdateStrategicModelComponent(ctx context.Context, req *StrategicModelComponentUpdateRequest, params UpdateStrategicModelComponentParams) (*StrategicModelComponentResponse, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
